<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOs0mFZy\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOs0mFZy/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOs0mFZy.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOs0mFZy\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOs0mFZy\App_KernelProdContainer([
    'container.build_hash' => 'Os0mFZy',
    'container.build_id' => '3bfd08db',
    'container.build_time' => 1616659169,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOs0mFZy');
