<?php

namespace ContainerOm3ffjn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M4CZkxNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m4CZkxN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m4CZkxN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'missions' => ['privates', '.errored..service_locator.m4CZkxN.App\\Entity\\Missions', NULL, 'Cannot autowire service ".service_locator.m4CZkxN": it references class "App\\Entity\\Missions" but no such service exists.'],
        ], [
            'missions' => 'App\\Entity\\Missions',
        ]);
    }
}
