<?php

namespace ContainerOm3ffjn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m4CZkxN.App\Entity\Missions' shared service.
     *
     * @return \App\Entity\Missions
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.m4CZkxN": it references class "App\\Entity\\Missions" but no such service exists.');
    }
}
