<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerThGtwZX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerThGtwZX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerThGtwZX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerThGtwZX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerThGtwZX\App_KernelDevDebugContainer([
    'container.build_hash' => 'ThGtwZX',
    'container.build_id' => 'a91b1611',
    'container.build_time' => 1616410406,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerThGtwZX');
