<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOm3ffjn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOm3ffjn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOm3ffjn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOm3ffjn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOm3ffjn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Om3ffjn',
    'container.build_id' => 'ac28e33c',
    'container.build_time' => 1616495322,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOm3ffjn');
