<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCjxEyIS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCjxEyIS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCjxEyIS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCjxEyIS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCjxEyIS\App_KernelDevDebugContainer([
    'container.build_hash' => 'CjxEyIS',
    'container.build_id' => '7bac28e8',
    'container.build_time' => 1616575879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCjxEyIS');
